using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Unicam.Paradigmi.Models.Entities
{
	public enum Categoria
	{
		// Narrativa (Fiction)
		ROMANZO, RACCONTI_BREVI, FANTASY, FANTASCIENZA, GIALLO_THRILLER, HORROR, AVVENTURA,
		ROMANZO_ROSA, ROMANZO_STORICO, NOIR, SATIRA, SAGGISTICA_NARRATIVA, DISTOPIA_UTOPIA,
		LETTERATURA_PER_BAMBINI, LETTERATURA_PER_GIOVANI_ADULTI_YA, GRAPHIC_NOVEL, ROMANZO_PSICOLOGICO,
		REALISMO_MAGICO,

		// Saggistica (Non-Fiction)
		BIOGRAFIE_E_AUTOBIOGRAFIE, MEMORIE, STORIA, FILOSOFIA, PSICOLOGIA, SCIENZA, ECONOMIA,
		POLITICA, SOCIOLOGIA, EDUCAZIONE, RELIGIONE_E_SPIRITUALITÀ, ARTE_E_DESIGN, VIAGGI,
		SALUTE_E_BENESSERE, CUCINA, MANUALISTICA_E_FAI_DA_TE, AUTO_AIUTO, ECONOMIA_DOMESTICA,
		CRITICA_LETTERARIA, GIORNALISMO,

		// Poesia
		POESIA_LIRICA, POESIA_EPICA, SONETTI, HAIKU, VERSI_LIBERI,

		// Teatro e Drammaturgia
		TRAGEDIA, COMMEDIA, DRAMMA_STORICO, MONOLOGHI, MUSICAL, SATIRA_TEATRALE,

		// Libri Tecnici e Accademici
		MANUALI_DI_INGEGNERIA, MEDICINA, INFORMATICA_E_TECNOLOGIA, MATEMATICA, SCIENZE_NATURALI,
		MANUALI_GIURIDICI, MANUALI_SCOLASTICI_E_UNIVERSITARI, LIBRI_DI_RICERCA,

		// Altri Generi e Categorie Speciali
		LIBRI_PER_BAMBINI_PICTURE_BOOKS, FUMETTI, ALMANACCHI, ENCICLOPEDIE, ATLANTI, CALENDARI_E_AGENDE,
		LIBRI_INTERATTIVI, LIBRI_AUDIO, E_BOOK
	}
}
